import { PrismaClient } from "@prisma/client";
import { Text } from "@radix-ui/themes";
import Head from "next/head";
import { api } from "~/utils/api";

export default function Home() {


  // const hello = api.post.hello.useQuery({ text: "from tRPC" });
  const hello = api.users.getUser.useQuery({ name: "kalpit_index" })

  return (
    <>
      <Head>
        <title>Kalpit-biz </title>
        <meta name="description" content="Generated by kalpit" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-white">
        <Text>
          {hello.data?.greeting}
        </Text>
      </main>


    </>
  );
}
